apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-service
  labels:
    apps: jobs-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jobs-service
  template:
    metadata:
      labels:
        component: jobs-service
    spec:
      containers:
      - name: jobs-service
        image: goodtalent/jobs-service:$COMMIT_SHA1
        imagePullPolicy: Always
        command: ["/bin/sh"]        
        args: ["-c","npm run start"]
        ports:
          - containerPort: 5002
            name: jobs
          - containerPort: 9001
            name: jobs-rpc
        env:
          - name: DATABASE
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: DATABASE
          - name: APP_NAME
            value: jobs-service
          - name: NODE_ENV
            value: production
          - name: GRPC_USER_CLIENT
            value: "5000"
          - name: GRPC_NOTIFY_CLIENT
            value: "5001"
          - name: PORT
            value: "5002"
          - name: FRONTEND_SERVER
            value: "https://goodtalent-e5d03.web.app"
          - name: DEBUG
            value: "true"
          - name: DECODE_TOKEN_URL
            value: "http://188.166.138.127/usermgt/api/v2/grpc/check-user-permissions"
          - name: secretToken
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: secretToken              
          - name: CLOUDINARY_NAME
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: CLOUDINARY_NAME  
          - name: HASH_SECRET
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: HASH_SECRET 
          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: CLOUDINARY_API_SECRET 
          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: jobs-env
                key: CLOUDINARY_API_KEY 
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jobs
  annotations:
    kubernetes.io/ingress.class: nginx #nginx prod-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2 #nginx re-write rule
  labels:
    app: jobs
  namespace: staging #master / staging
spec:
  rules:
    - http:
        paths:
        - path: /jobs(/|$)(.*)
          backend:
            serviceName: jobs
            servicePort: 5002
        - path: /jobs-rpc
          backend:
            serviceName: jobs
            servicePort: 5000

---
apiVersion: v1
kind: Service
metadata: 
  name: jobs
  labels:
    app: jobs
  namespace: staging #default / staging
spec:
  type: ClusterIP  
  selector:
    component: jobs-service
  ports:
    - name: jobs
      port: 5002
      targetPort: 5002
    - name: jobs-rpc
      port: 9001
      targetPort: 9001
